###ICD 9 groups###
Number.of.observations.ICD_9_groups <- setNames(data.frame(matrix(ncol = 2, nrow = 86)), c("1", "n"))

Number.of.observations.ICD_9_groups$Diagnosis <- c("Infectious and parasitic diseases", 
                                                   "Neoplasms", 
                                                   "Neoplasms of oral cavity",
                                                   "Neoplasms of digestive organs and peritoneum",
                                                   "Neoplasms of respiratory and intrathoracic organs",
                                                   "Neoplasms of bone connective tissue skin and breast",
                                                   "Kaposis sarcoma",
                                                   "Malignant neoplasms of genitourinary organs",
                                                   "Malignant neoplasms of other and unspecified sites",
                                                   "Malignant neoplasms of lymphatic and hematopoietic tissue",
                                                   "Benign neoplasms",
                                                   "Carcinoma in situ",
                                                   "Neoplasms of uncertain behavior",
                                                   "Neoplasms of unspecified nature",
                                                   "Malignant neoplasm of skin ",
                                                   "Endocrine metabolic immunity disorders", 
                                                   "Diseases of blood",
                                                   "Psychiatric diagnoses", 
                                                   "Organic psychotic conditions",
                                                   "Senile and presenile organic psychotic conditions",
                                                   "Alcoholic psychoses",
                                                   "Drug psychoses",
                                                   "Transient organic psychotic conditions",
                                                   "Other organic psychotic conditions chronic",
                                                   "Other psychoses",
                                                   "Schizophrenic psychoses",
                                                   "Affective psychoses",
                                                   "Paranoid states",
                                                   "Other nonorganic psychoses",
                                                   "Psychoses with origin specific to childhood",
                                                   "Neurotic disorders personality disorders and nonpsychotic mental disorders",
                                                   "Neurotic disorders",
                                                   "Personality disorders",
                                                   "Sexual deviations",
                                                   "Psychoactive substance",
                                                   "Alcohol dependence syndrome",
                                                   "Drug dependence",
                                                   "Nondependent aduse of drugs",
                                                   "Other primarily adult onset",
                                                   "Physiological malfunction arising from mental factors",
                                                   "Special symptoms or syndromes not elsewhere classified",
                                                   "Acute reaction to stress",
                                                   "Adjustment reaction",
                                                   "Specific nonpsychotic mental disorders following brain damage",
                                                   "Depressive disorder not elsewhere classified",
                                                   "Mental disorders childhood",
                                                   "Disturbance of conduct not elsewhere classified",
                                                   "Disturbance of emotions specific to childhood and adolescence",
                                                   "Hyperkinetic syndrome of childhood",
                                                   "Specific delays in development",
                                                   "Psychic factors",
                                                   "Mental retardation",
                                                   "Diseases of nervous system", 
                                                   "Diseases of circulatory system", 
                                                   "Acute rheumatic fever",
                                                   "Chronic rheumatic heart disease",
                                                   "Hypertensive disease",
                                                   "Ischemic heart disease",
                                                   "Diseases of pulmonary circulation",
                                                   "Other heart diseases",
                                                   "Cerebrovascular disease",
                                                   "Diseases of arteries and capillaries",
                                                   "Diseases of veins and lymphatics and other",
                                                   "diseases of respiratory system", 
                                                   "Acute respiratory infections",
                                                   "Other diseases of the upper respiratory tract",
                                                   "Pneumonia and influenza",
                                                   "Chronic obstructive pulmonary disease and allied conditions",
                                                   "Pneumoconioses and other lung diseases due to external agents",
                                                   "Other diseases of respiratory system",
                                                   "Diseases of digestive system", 
                                                   "Diseases of genitourinary system", 
                                                   "Nephritis nephrotic sydrome and nephrosis",
                                                   "Other diseases of urinary system",
                                                   "Diseases of breast",
                                                   "complicatoins of pregnancy and childbirth", 
                                                   "Diseases of skin", 
                                                   "Infections of skin",
                                                   "Inflammatory conditions of skin",
                                                   "Psoriasis and similar disorders",
                                                   "Other diseases of skin",
                                                   "Diseases of musculoskeletal and connective tissue", 
                                                   "Congenital anomalies", 
                                                   "Conditions of perinatal period", 
                                                   "Ill defined conditions", 
                                                   "Injury and poisoning"
)

for(i in 1:86){Number.of.observations.ICD_9_groups[i,2] <- nrow(ICD_9_code_groups[[i]])}
Number.of.observations.ICD_9_groups[,1]<- NULL

###ICD 10###
Number.of.observations.ICD_10_groups <- setNames(data.frame(matrix(ncol = 2, nrow = 5)), c("1", "n"))

Number.of.observations.ICD_10_groups$Diagnosis <- c("Manic episode",
                                                    "Bipolar affective disorder",
                                                    "Depressive episode",
                                                    "Recurrent depressive disorder",
                                                    "Persistent mood affective disorders")

for(i in 1:5){Number.of.observations.ICD_10_groups[i,2] <- nrow(ICD_10_code_groups[[i]])}
Number.of.observations.ICD_10_groups[,1]<- NULL




###primary diagnosis ICD 9###
Number.of.observations.primary.diagnosis.ICD_9_groups <- setNames(data.frame(matrix(ncol = 2, nrow = 86)), c("1", "n"))

Number.of.observations.primary.diagnosis.ICD_9_groups$Diagnosis <- c("Infectious and parasitic diseases", 
                                                                      "Neoplasms", 
                                                                      "Neoplasms of oral cavity",
                                                                      "Neoplasms of digestive organs and peritoneum",
                                                                      "Neoplasms of respiratory and intrathoracic organs",
                                                                      "Neoplasms of bone connective tissue skin and breast",
                                                                      "Kaposis sarcoma",
                                                                      "Malignant neoplasms of genitourinary organs",
                                                                      "Malignant neoplasms of other and unspecified sites",
                                                                      "Malignant neoplasms of lymphatic and hematopoietic tissue",
                                                                      "Benign neoplasms",
                                                                      "Carcinoma in situ",
                                                                      "Neoplasms of uncertain behavior",
                                                                      "Neoplasms of unspecified nature",
                                                                      "Malignant neoplasm of skin ",
                                                                      "Endocrine metabolic immunity disorders", 
                                                                      "Diseases of blood",
                                                                      "Psychiatric diagnoses", 
                                                                      "Organic psychotic conditions",
                                                                      "Senile and presenile organic psychotic conditions",
                                                                      "Alcoholic psychoses",
                                                                      "Drug psychoses",
                                                                      "Transient organic psychotic conditions",
                                                                      "Other organic psychotic conditions chronic",
                                                                      "Other psychoses",
                                                                      "Schizophrenic psychoses",
                                                                      "Affective psychoses",
                                                                      "Paranoid states",
                                                                      "Other nonorganic psychoses",
                                                                      "Psychoses with origin specific to childhood",
                                                                      "Neurotic disorders personality disorders and nonpsychotic mental disorders",
                                                                      "Neurotic disorders",
                                                                      "Personality disorders",
                                                                      "Sexual deviations",
                                                                      "Psychoactive substance",
                                                                      "Alcohol dependence syndrome",
                                                                      "Drug dependence",
                                                                      "Nondependent aduse of drugs",
                                                                      "Other primarily adult onset",
                                                                      "Physiological malfunction arising from mental factors",
                                                                      "Special symptoms or syndromes not elsewhere classified",
                                                                      "Acute reaction to stress",
                                                                      "Adjustment reaction",
                                                                      "Specific nonpsychotic mental disorders following brain damage",
                                                                      "Depressive disorder not elsewhere classified",
                                                                      "Mental disorders childhood",
                                                                      "Disturbance of conduct not elsewhere classified",
                                                                      "Disturbance of emotions specific to childhood and adolescence",
                                                                      "Hyperkinetic syndrome of childhood",
                                                                      "Specific delays in development",
                                                                      "Psychic factors",
                                                                      "Mental retardation",
                                                                      "Diseases of nervous system", 
                                                                      "Diseases of circulatory system", 
                                                                      "Acute rheumatic fever",
                                                                      "Chronic rheumatic heart disease",
                                                                      "Hypertensive disease",
                                                                      "Ischemic heart disease",
                                                                      "Diseases of pulmonary circulation",
                                                                      "Other heart diseases",
                                                                      "Cerebrovascular disease",
                                                                      "Diseases of arteries and capillaries",
                                                                      "Diseases of veins and lymphatics and other",
                                                                      "diseases of respiratory system", 
                                                                      "Acute respiratory infections",
                                                                      "Other diseases of the upper respiratory tract",
                                                                      "Pneumonia and influenza",
                                                                      "Chronic obstructive pulmonary disease and allied conditions",
                                                                      "Pneumoconioses and other lung diseases due to external agents",
                                                                      "Other diseases of respiratory system",
                                                                      "Diseases of digestive system", 
                                                                      "Diseases of genitourinary system", 
                                                                      "Nephritis nephrotic sydrome and nephrosis",
                                                                      "Other diseases of urinary system",
                                                                      "Diseases of breast",
                                                                      "complicatoins of pregnancy and childbirth", 
                                                                      "Diseases of skin", 
                                                                      "Infections of skin",
                                                                      "Inflammatory conditions of skin",
                                                                      "Psoriasis and similar disorders",
                                                                      "Other diseases of skin",
                                                                      "Diseases of musculoskeletal and connective tissue", 
                                                                      "Congenital anomalies", 
                                                                      "Conditions of perinatal period", 
                                                                      "Ill defined conditions", 
                                                                      "Injury and poisoning"
)

for(i in 1:86){Number.of.observations.primary.diagnosis.ICD_9_groups[i,2] <- nrow(primary.diagnosis.ICD_9_code_groups[[i]])}
Number.of.observations.primary.diagnosis.ICD_9_groups[,1]<- NULL

#######
#Procedure groups
Number.of.observations.procedure_groups <- setNames(data.frame(matrix(ncol = 2, nrow = 17)), c("1", "n"))

Number.of.observations.procedure_groups$Diagnosis <- c("Operations_on_the_nervous_system",
                                                                     "Operations_on_the_endocrine_system",
                                                                     "Operations_on_the_eye",
                                                                     "Operations_on_the_ear",
                                                                     "Operations_on_the_nose_mouth_pharynx",
                                                                     "Operations_on_the_respiratory_system",
                                                                     "Operations_on_the_cardiovascular_system",
                                                                     "Operations_on_the_hemic_and_lymphatic_system",
                                                                     "Operations_on_the_digestive_system",
                                                                     "Operations_on_the_urinary_system",
                                                                     "Operations_on_the_male_genital_organs",
                                                                     "Operations_on_the_female_genital_organs",
                                                                     "Obstetrical_procedures",
                                                                     "Operations_on_the_musculoskeletal_system",
                                                                     "Operations_on_the_integumentary_system",
                                                                     "Miscellaneous_diagnostic_and_therapeutic_procedures",
                                                                     "Procedures_related_to_psyche"
)

for(i in 1:17){Number.of.observations.procedure_groups[i,2] <- nrow(procedure_groups[[i]])}
Number.of.observations.procedure_groups[,1]<- NULL
